global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: bff
    metrics_path: /metrics
    static_configs:
      - targets:
          - web-bff-api:5001

  - job_name: polymarket-kafka
    metrics_path: /metrics
    static_configs:
      - targets:
          - polymarket-event-producer:9101

  - job_name: stock-news-kafka
    metrics_path: /metrics
    static_configs:
      - targets:
          - stock-news-event-producer:9102

  - job_name: stock-analytics-kafka
    metrics_path: /metrics
    static_configs:
      - targets:
          - stock-analytics-event-producer:9103

  - job_name: strategy-injestor
    metrics_path: /metrics
    static_configs:
      - targets:
          - polymarket-event-consumer:9104
          - stock-news-event-consumer:9104
          - stock-analytics-event-consumer:9104